# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: peiyong's place
email: pygoodmood@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Hi there, this is peiyong's place. I like reading and travelling. I did skydiving in NZ and diving in bali island, I climbed a volcano Indonisia, all those experiences are fun and awesome. My job is writing code and do computer vision. I come from China and now stay in Singapore.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pygoodmood.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: pygoodmood

# Build settings
markdown: kramdown
